// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: slot.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// Create a Game
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*NewGameReply, error)
	// Check if a game exists
	GameExists(ctx context.Context, in *ShowGameRequest, opts ...grpc.CallOption) (*GameExistsReply, error)
	// Play an existing game
	PlayGame(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*ResultPlayReply, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*NewGameReply, error) {
	out := new(NewGameReply)
	err := c.cc.Invoke(ctx, "/GameService/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GameExists(ctx context.Context, in *ShowGameRequest, opts ...grpc.CallOption) (*GameExistsReply, error) {
	out := new(GameExistsReply)
	err := c.cc.Invoke(ctx, "/GameService/GameExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) PlayGame(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*ResultPlayReply, error) {
	out := new(ResultPlayReply)
	err := c.cc.Invoke(ctx, "/GameService/PlayGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations should embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	// Create a Game
	CreateGame(context.Context, *CreateGameRequest) (*NewGameReply, error)
	// Check if a game exists
	GameExists(context.Context, *ShowGameRequest) (*GameExistsReply, error)
	// Play an existing game
	PlayGame(context.Context, *PlayRequest) (*ResultPlayReply, error)
}

// UnimplementedGameServiceServer should be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) CreateGame(context.Context, *CreateGameRequest) (*NewGameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameServiceServer) GameExists(context.Context, *ShowGameRequest) (*GameExistsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameExists not implemented")
}
func (UnimplementedGameServiceServer) PlayGame(context.Context, *PlayRequest) (*ResultPlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayGame not implemented")
}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GameExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GameExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/GameExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GameExists(ctx, req.(*ShowGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_PlayGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).PlayGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameService/PlayGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).PlayGame(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "GameExists",
			Handler:    _GameService_GameExists_Handler,
		},
		{
			MethodName: "PlayGame",
			Handler:    _GameService_PlayGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slot.proto",
}
