// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID         string `json:"id"`
	IsFinished bool   `json:"isFinished"`
	CreatedAt  string `json:"createdAt"`
}

type GameID struct {
	ID string `json:"id"`
}

type NewGame struct {
	WinChance    int `json:"winChance"`
	TotalJogadas int `json:"totalJogadas"`
}
