// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.3
// source: gamevitaedashboard.proto

package gameVitaeDashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// parameter retrieve data from  common.Session
type SessionParameterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User      string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PageIndex int64  `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize  int64  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderBy   string `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Asc       bool   `protobuf:"varint,5,opt,name=asc,proto3"`
}

func (x *SessionParameterRequest) Reset() {
	*x = SessionParameterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gamevitaedashboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionParameterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParameterRequest) ProtoMessage() {}

func (x *SessionParameterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamevitaedashboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParameterRequest.ProtoReflect.Descriptor instead.
func (*SessionParameterRequest) Descriptor() ([]byte, []int) {
	return file_gamevitaedashboard_proto_rawDescGZIP(), []int{0}
}

func (x *SessionParameterRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SessionParameterRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *SessionParameterRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SessionParameterRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *SessionParameterRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

// parameter retrieve data from  common.Session
type SessionParameterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*SessionRecordSet `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalRows int64               `protobuf:"varint,2,opt,name=totalRows,proto3" json:"totalRows,omitempty"`
}

func (x *SessionParameterReply) Reset() {
	*x = SessionParameterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gamevitaedashboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionParameterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParameterReply) ProtoMessage() {}

func (x *SessionParameterReply) ProtoReflect() protoreflect.Message {
	mi := &file_gamevitaedashboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParameterReply.ProtoReflect.Descriptor instead.
func (*SessionParameterReply) Descriptor() ([]byte, []int) {
	return file_gamevitaedashboard_proto_rawDescGZIP(), []int{1}
}

func (x *SessionParameterReply) GetData() []*SessionRecordSet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SessionParameterReply) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

type SessionRecordSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User       string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	GameId     int64  `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	DeviceId   int64  `protobuf:"varint,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Date       string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	ClinicId   int64  `protobuf:"varint,6,opt,name=clinicId,proto3" json:"clinicId,omitempty"`
	RowVersion string `protobuf:"bytes,7,opt,name=rowVersion,proto3" json:"rowVersion,omitempty"`
}

func (x *SessionRecordSet) Reset() {
	*x = SessionRecordSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gamevitaedashboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRecordSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRecordSet) ProtoMessage() {}

func (x *SessionRecordSet) ProtoReflect() protoreflect.Message {
	mi := &file_gamevitaedashboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRecordSet.ProtoReflect.Descriptor instead.
func (*SessionRecordSet) Descriptor() ([]byte, []int) {
	return file_gamevitaedashboard_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRecordSet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionRecordSet) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SessionRecordSet) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SessionRecordSet) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SessionRecordSet) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SessionRecordSet) GetClinicId() int64 {
	if x != nil {
		return x.ClinicId
	}
	return 0
}

func (x *SessionRecordSet) GetRowVersion() string {
	if x != nil {
		return x.RowVersion
	}
	return ""
}

var File_gamevitaedashboard_proto protoreflect.FileDescriptor

var file_gamevitaedashboard_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x61, 0x6d, 0x65, 0x76, 0x69, 0x74, 0x61, 0x65, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x63,
	0x22, 0x5c, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x6f, 0x77, 0x73, 0x22, 0xba,
	0x01, 0x0a, 0x10, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x53, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x6f, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x6f, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x5d, 0x0a, 0x10, 0x47,
	0x61, 0x6d, 0x65, 0x56, 0x69, 0x74, 0x61, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x49, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x56, 0x69, 0x74, 0x61, 0x65, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gamevitaedashboard_proto_rawDescOnce sync.Once
	file_gamevitaedashboard_proto_rawDescData = file_gamevitaedashboard_proto_rawDesc
)

func file_gamevitaedashboard_proto_rawDescGZIP() []byte {
	file_gamevitaedashboard_proto_rawDescOnce.Do(func() {
		file_gamevitaedashboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_gamevitaedashboard_proto_rawDescData)
	})
	return file_gamevitaedashboard_proto_rawDescData
}

var file_gamevitaedashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gamevitaedashboard_proto_goTypes = []interface{}{
	(*SessionParameterRequest)(nil), // 0: SessionParameterRequest
	(*SessionParameterReply)(nil),   // 1: SessionParameterReply
	(*SessionRecordSet)(nil),        // 2: sessionRecordSet
}
var file_gamevitaedashboard_proto_depIdxs = []int32{
	2, // 0: SessionParameterReply.data:type_name -> sessionRecordSet
	0, // 1: GameVitaeService.RetrieveSessionData:input_type -> SessionParameterRequest
	1, // 2: GameVitaeService.RetrieveSessionData:output_type -> SessionParameterReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gamevitaedashboard_proto_init() }
func file_gamevitaedashboard_proto_init() {
	if File_gamevitaedashboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gamevitaedashboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionParameterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gamevitaedashboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionParameterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gamevitaedashboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRecordSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gamevitaedashboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamevitaedashboard_proto_goTypes,
		DependencyIndexes: file_gamevitaedashboard_proto_depIdxs,
		MessageInfos:      file_gamevitaedashboard_proto_msgTypes,
	}.Build()
	File_gamevitaedashboard_proto = out.File
	file_gamevitaedashboard_proto_rawDesc = nil
	file_gamevitaedashboard_proto_goTypes = nil
	file_gamevitaedashboard_proto_depIdxs = nil
}
